### ISSUE TITLE
Провести проверку на большом файле

### ISSUE THREAD

**Issue by alexkoss** [DaniilDDDDD/BaltInfoCom#1]
Добрый день! Меня зовут Александр, сотрудник компании БалтИнфоКом.

Предлагаю осуществить проверку на большом файле.

Файл: https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

В ответе должно быть количество групп и время выполнения.

**Comment by DaniilDDDDD** [comment]
В данный момент на датасете в 12.000.000 значений работает очень медленно(
Пытаюсь найти более оптимальное решение!

**Comment by alexkoss** [comment]
ок, ждём

**Comment by DaniilDDDDD** [comment]
Придумал альтернативный алгоритм.
Скоро залью код.

**Comment by DaniilDDDDD** [comment]
Залил код. Ответ хранится в файла answerOnDownloadedFileBig.txt.

**Comment by alexkoss** [comment]
_В ответе должно быть количество групп и время выполнения._

**Comment by DaniilDDDDD** [comment]
Изначально в последней строке время работы выводилось.
Перенёс в первую.
Залил.
